language: rust
cache: cargo
rust:
  - stable
  - nightly
os:
  - linux
  - osx

matrix:
  fast_finish: true

env:
  global:
    - RUST_BACKTRACE=1

script:
  - cargo build --all --verbose
  - cargo test -- --nocapture
