[[instance]]
server = "irc.mozilla.org"
nickname = "nick"
# nick_password = "pass"
channels = [
    "#my_channel"
]
port = 6697
use_tls = true
should_ghost = true
ghost_sequence = ["RECOVER"]
burst_window_length = 5
max_messages_in_burst = 4
encoding = "UTF-8"
