[package]
name = "reval"
version = "0.1.0"
authors = ["panicbit <panicbit.dev@gmail.com>"]
edition = "2018"

[dependencies]
playbot_ng = { path = ".." }
failure = "0.1"
tokio = { version = "0.2", features = ["full"] }
rustyline = "6.2"
shared_str = "0.1"
slog = "2.5"
