[package]
name = "reval"
version = "0.1.0"
authors = ["panicbit <panicbit.dev@gmail.com>"]
edition = "2018"

[dependencies]
playbot_ng = { path = ".." }
failure = "0.1.2"
tokio = "0.1.11"
rustyline = "5.0.0"
shared_str = "0.1.0"
slog = "2.4.1"
